name: Snyk IaC Test

on:
  pull_request:
    branches:
      - main

jobs:
  snyk_iac_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk IaC test
        run: snyk iac test 
